name: sspi
description: College management application

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.19.0-444.6.beta <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  get: ^4.6.5
  google_fonts: ^4.0.1
  firebase_core: ^2.4.1
  firebase_storage: ^11.0.10
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  flutter_svg: ^1.1.6
  url_launcher: ^6.1.8
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.0.0+2
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/sspi_logo.png"


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
